### ISSUE TITLE
[1.7.10] water glitch

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/AnimFix#8] opened 2022-08-27 21:37 UTC
Mods list :

animfix-mc1.7.10-2.2.0
falsepatternlib-mc1.7.10-0.10.5
SpongeMixins-1.5.0(from (https://github.com/GTNewHorizons))

when i remove anim fix i don't get this issue
this issue does not happen with animfix-mc1.7.10-2.1.0

seed : 6072332008759161860
location : -5 75 129

logs :
[latest.log](https://github.com/FalsePattern/AnimFix/files/9438711/latest.log)

screenshot : 
![image](https://user-images.githubusercontent.com/42176772/187048855-d05985fe-4864-4959-96a2-3887e1c6d85a.png)

**Comment by FalsePattern** [comment] 2022-08-28 11:59
Duplicate of #7

**Closed by FalsePattern** 2022-08-28 11:59 UTC
